<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Members Report</title>
    <style>
        /* Reset CSS for PDF */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'DejaVu Sans', 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            padding: 20px;
        }
        
        /* Header Styles */
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #4e73df;
            padding-bottom: 15px;
        }
        
        .header h1 {
            color: #4e73df;
            font-size: 24px;
            margin-bottom: 5px;
        }
        
        .header p {
            color: #666;
            font-size: 11px;
        }
        
        /* Title Section */
        .title-section {
            margin-bottom: 20px;
        }
        
        .title-section h2 {
            font-size: 18px;
            color: #333;
            border-left: 4px solid #4e73df;
            padding-left: 10px;
            margin-bottom: 15px;
        }
        
        /* Summary Cards */
        .summary {
            display: flex;
            margin-bottom: 25px;
            gap: 15px;
        }
        
        .summary-card {
            flex: 1;
            background: #f8f9fc;
            border: 1px solid #e3e6f0;
            border-radius: 8px;
            padding: 12px;
            text-align: center;
        }
        
        .summary-card .label {
            font-size: 11px;
            color: #666;
            margin-bottom: 5px;
        }
        
        .summary-card .value {
            font-size: 20px;
            font-weight: bold;
            color: #4e73df;
        }
        
        /* Table Styles */
        .table-container {
            margin-top: 20px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        th {
            background-color: #4e73df;
            color: white;
            padding: 10px 8px;
            text-align: center;
            font-weight: bold;
            font-size: 11px;
            border: 1px solid #3a5ccc;
        }
        
        td {
            padding: 8px;
            text-align: center;
            border: 1px solid #ddd;
            font-size: 11px;
        }
        
        tr:nth-child(even) {
            background-color: #f8f9fc;
        }
        
        /* Footer */
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
        
        .footer p {
            margin: 3px 0;
        }
        
        /* Badge/Signature */
        .signature {
            margin-top: 30px;
            display: flex;
            justify-content: flex-end;
        }
        
        .signature-box {
            text-align: center;
            width: 250px;
        }
        
        .signature-line {
            border-top: 1px solid #333;
            margin-top: 40px;
            padding-top: 5px;
            font-size: 10px;
        }
        
        /* Print Optimization */
        @media print {
            body {
                padding: 0;
            }
            .no-print {
                display: none;
            }
        }
        
        /* Price formatting */
        .price {
            font-weight: bold;
            color: #1cc88a;
        }
        
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
        }
        
        .badge-basic {
            background-color: #36b9cc;
            color: white;
        }
        
        .badge-premium {
            background-color: #f6c23e;
            color: #333;
        }
        
        .badge-vip {
            background-color: #e74a3b;
            color: white;
        }
        
        .text-center {
            text-align: center;
        }
        
        .text-right {
            text-align: right;
        }
        
        .text-left {
            text-align: left;
        }
        
        .font-bold {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Membership Report</h1>
        <p>Generated on: {{ $generatedDate }} | Generated by: {{ $generatedBy }}</p>
    </div>

    <div class="title-section">
        <h2>Membership Summary</h2>
    </div>

    <!-- Summary Cards -->
    <div class="summary">
        <div class="summary-card">
            <div class="label">Total Members</div>
            <div class="value">{{ $totalMembers }}</div>
        </div>
        <div class="summary-card">
            <div class="label">Total Value</div>
            <div class="value">Rp {{ number_format($totalPrice, 0, ',', '.') }}</div>
        </div>
        <div class="summary-card">
            <div class="label">Average Price</div>
            <div class="value">
                Rp {{ $totalMembers > 0 ? number_format($totalPrice / $totalMembers, 0, ',', '.') : '0' }}
            </div>
        </div>
    </div>

    <!-- Members Table -->
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th width="5%">No</th>
                    <th width="40%">Membership Grade</th>
                    <th width="30%">Price</th>
                    <th width="25%">Access Level</th>
                </tr>
            </thead>
            <tbody>
                @forelse($members as $index => $member)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="text-left">
                        <strong>{{ $member->name }}</strong>
                    </td>
                    <td class="text-center">
                        <span class="price">Rp {{ number_format($member->price, 0, ',', '.') }}</span>
                    </td>
                    <td class="text-center">
                        @php
                            $badgeClass = '';
                            switch(strtoupper($member->name)) {
                                case 'BASIC':
                                    $badgeClass = 'badge-basic';
                                    break;
                                case 'PREMIUM':
                                    $badgeClass = 'badge-premium';
                                    break;
                                case 'VIP':
                                    $badgeClass = 'badge-vip';
                                    break;
                                default:
                                    $badgeClass = 'badge-basic';
                            }
                        @endphp
                        <span class="badge {{ $badgeClass }}">
                            {{ ucfirst(strtolower($member->name)) }}
                        </span>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="text-center">No members data available</td>
                </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="3" class="text-right font-bold">Total Value:</th>
                    <th class="text-center price">
                        Rp {{ number_format($totalPrice, 0, ',', '.') }}
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- Additional Info -->
    <div class="table-container">
        <table style="width: 50%; margin-top: 20px;">
            <tr>
                <th width="50%">Statistics</th>
                <th width="50%">Value</th>
            </tr>
            <tr>
                <td>Highest Price</td>
                <td class="price">
                    Rp {{ $members->isNotEmpty() ? number_format($members->max('price'), 0, ',', '.') : '0' }}
                </td>
            </tr>
            <tr>
                <td>Lowest Price</td>
                <td class="price">
                    Rp {{ $members->isNotEmpty() ? number_format($members->min('price'), 0, ',', '.') : '0' }}
                </td>
            </tr>
        </table>
    </div>

    <!-- Signature Section -->
    <div class="signature">
        <div class="signature-box">
            <div class="signature-line">
                {{ $generatedBy }}
                <br>
                <small>System Administrator</small>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This report was generated automatically by the system.</p>
        <p>&copy; {{ date('Y') }} Blogs Management System. All rights reserved.</p>
        <p>Page 1 of 1</p>
    </div>
</body>
</html>